### GET All Users
GET http://localhost:5000/api/v1/users

### GET ID User
GET http://localhost:5000/api/v1/users

### Login User
POST http://localhost:5000/api/v1/user/login
Content-Type: application/json

{
    "email": "someone@gmail.com",
    "password": "somepassword"
}

### Register User
POST http://localhost:5000/api/v1/user/register
Content-Type: application/json

{
    "email": "someone@gmail.com",
    "password": "somepassword",
    "fullname": "My Name Is Some People"
}

### PATCH ID User
PATCH http://localhost:5000/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNmFiYWY1Yjk4ZGU1MjdiZmY1YWZiNyIsImlhdCI6MTYzNDM4NDYzMH0.2eaP1yHxCyLQFkL4IJCrLnqzqu_mstx-cIw4pHnJAJk

{
    "fullname": "My Name Is Some People",
    "phone": "0101010101"
}

### DELETE ID User
DELETE http://localhost:5000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNmFiODdlMTY3ZjA5NzkwYzNiMjQ1ZiIsImlhdCI6MTYzNDM4NDAwMH0.TPXD_pAKdwcVNZqimlgEpWq7N7zbkIM9xGltsD5LB3g

### GET User Details
GET http://localhost:5000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNmFiYWY1Yjk4ZGU1MjdiZmY1YWZiNyIsImlhdCI6MTYzNDM4NDYzMH0.2eaP1yHxCyLQFkL4IJCrLnqzqu_mstx-cIw4pHnJAJk